### ISSUE TITLE
Minskins 7**2

### ISSUE THREAD

**Issue by simandebvu** [Bismarck-GM/SQL-ZOO#1]
Awesome project !! 👍 

One picture about your `README`

![YOURREADME...](https://media1.giphy.com/media/Jq7WUBf71Gju1vTe2A/200w.webp?cid=ecf05e479e7d9ce393be79c8ad305a2ea8449b9a1b1c5a5e&rid=200w.webp)

They do say a picture can say a thousand words. 😉

**Comment by Bismarck-GM** [comment]
Applied changes to readme as the Master of READMES asked.
